/* RATACODE · el español de la casa (R21).
 *
 * Son los diccionarios del motor DSH (40 espacios de nombres, 1236 textos) pasados al español,
 * medidos de los propios bundles instalados (`trabajo\R21\sacar-diccionarios.mjs`).
 * Aquí NO se traduce nada a mano sobre la pantalla: este guion sólo deja los
 * textos en `window.__RATACODE_ES`, y el plugin de cliente de la piel los
 * registra por la vía OFICIAL de idiomas (`ctx.locale.addLanguage` +
 * `ctx.locale.register`). Así el idioma se cambia desde Ajustes › General ›
 * Language, sale «Español» en la lista, y el inglés y el chino siguen ahí.
 *
 * Lo pone el index (junto a `ratacode-piel.js`), antes del módulo de la piel:
 * cuando el idioma se registra, ya está este texto, y no hay parpadeo en inglés.
 */
window.__RATACODE_ES = {
  "approval": {
   "waiting": "Esperando aprobación",
   "detail.aria": "Detalles de la aprobación",
   "escalation": "La herramienta {toolName} pide ejecución con privilegios",
   "reject": "Rechazar",
   "allowOnce": "Permitir una vez",
  },
  "chat": {
   "view.chat": "Chat",
   "number.groupSeparator": ",",
   "duration.compactSeconds": "{seconds}s",
   "duration.compactMinutes": "{minutes}m{seconds}s",
   "duration.milliseconds": "{milliseconds}ms",
   "stats.counts": "{turns} vueltas {steps} pasos",
   "stats.cacheHit": "Aciertos de caché {percent}%",
   "stats.dialog.title": "Estadísticas de la sesión",
   "stats.dialog.usageTitle": "Uso de tokens",
   "stats.dialog.llmTime": "Tiempo del LLM",
   "stats.dialog.toolTime": "Tiempo de herramientas",
   "stats.dialog.ttft": "Tiempo medio hasta el primer token (TTFT)",
   "stats.dialog.speed": "Tokens por segundo (TPS)",
   "chat.loadingHistory": "Cargando el historial…",
   "chat.loadError": "No se pudo cargar el historial: {message} ({code})",
   "chat.loadOlder": "Cargar anteriores",
   "chat.toBottom": "Volver abajo",
   "chat.deepDiving": "Royendo…",
   "chat.turnNavigation.label": "Navegación por vueltas",
   "chat.turnNavigation.jump": "Ir a la vuelta {turn}",
   "chat.turnNavigation.jumpLoad": "Cargar e ir a la vuelta {turn}",
   "chat.turnNavigation.turn": "Vuelta {turn}",
   "settings.transcript.title": "Visualización de la conversación",
   "settings.transcript.description": "Controla el contenido del proceso en las vueltas ya terminadas",
   "settings.transcript.normal": "Normal",
   "settings.transcript.compact": "Compacto",
   "fileOpen.title": "No se pudo abrir el fichero",
   "fileOpen.unknown": "No se pudo abrir este fichero",
   "message.extraBlock": "Bloque de contenido adicional",
   "message.systemPrompt": "Instrucciones",
   "message.systemPromptUpdate": "Actualización de instrucciones",
   "message.contextInjection": "Soplos del motor",
   "message.contextRecall": "Recuerdo de la sesión",
   "message.referenceSummary": "Sesión referenciada · {labels}",
   "message.referenceSeparator": ", ",
   "message.context.instructions.loaded": "cargadas",
   "message.context.instructions.added": "añadidas",
   "message.context.instructions.updated": "actualizadas",
   "message.context.instructions.removed": "quitadas",
   "message.context.catalog.replaced": "Catálogo de reemplazo",
   "message.context.catalog.more": "… {count} más",
   "message.context.snapshot.supersedes": "Sustituye a las instantáneas anteriores",
   "message.context.relay.from": "Desde la sesión {session}",
   "message.context.recall.counts": "{retained} conservados · {omitted} omitidos",
   "message.context.recall.truncated": "truncado",
   "message.compaction": "Contexto compactado",
   "message.compaction.running": "Compactando el contexto…",
   "message.compaction.completed": "Compactados {items} elementos del historial (~{tokens} tokens)",
   "message.compaction.expand": "Ver el resumen de la compactación",
   "message.compaction.unavailable": "Resumen de compactación no disponible",
   "message.compaction.commandTitle": "compact",
   "message.think": "Rumiar",
   "message.unknownSurface": "Evento de superficie desconocido: {type}",
   "message.unknownBlock": "Bloque de contenido desconocido",
   "message.turnProcess.toolCalls.one": "{count} llamada a herramienta",
   "message.turnProcess.toolCalls.other": "{count} llamadas a herramienta",
   "message.turnProcess.messages.one": "{count} mensaje",
   "message.turnProcess.messages.other": "{count} mensajes",
   "message.turnProcess.subagents.one": "{count} subagente",
   "message.turnProcess.subagents.other": "{count} subagentes",
   "message.turnProcess.thoughtForAWhile": "Rumió un rato",
   "message.turnProcess.separator": " · ",
   "message.stopped": "Detenido",
   "message.branch": "Ramificar en una conversación nueva",
   "message.branchUnavailable": "Sólo disponible en el último mensaje de una vuelta terminada",
   "message.retry.active": "Reintentando la petición al modelo",
   "message.retry.cancelled": "Reintento de la petición al modelo cancelado",
   "message.retry.started": "Petición al modelo reintentada",
   "message.retry.scheduled": "Esperando para reintentar la petición al modelo",
   "message.retry.status": "{label} ({retry}/{maximum}) · {seconds}s",
   "message.retry.delay": "Retardo del reintento: ",
   "message.retry.failure": "Motivo del fallo: ",
   "message.failure.auth": "La clave de API no es válida",
   "message.turnError": "Esta vuelta ha fallado",
   "message.maxTokens": "Se alcanzó el límite de tokens de salida",
   "message.maxTokens.hint": "La respuesta se cortó; lo anterior se conserva en la conversación. Envía \"continue\" para que el modelo continúe.",
   "message.ranFor": "Duró {duration}",
   "message.tokensPerSecond": "{tps} tok/s",
   "message.turnUsage.title": "Uso de la vuelta",
   "message.turnUsage.consumed": "Uso {total}",
   "message.turnUsage.model": "Proveedor / modelo",
   "message.turnUsage.cacheHit": "Aciertos de caché",
   "message.turnUsage.input": "Entrada sin caché",
   "message.turnUsage.cacheRead": "Entrada cacheada",
   "message.turnUsage.cacheWrite": "Escritura en caché",
   "message.turnUsage.output": "Salida",
   "message.turnUsage.reasoning": " ({tokens} de razonamiento)",
   "message.turnUsage.count": "{count} tok",
   "message.turnTime.title": "Tiempo y velocidad de la vuelta",
   "message.turnTime.duration": "Tiempo total de ejecución",
   "message.turnTime.speed": "Tokens por segundo (TPS)",
   "message.turnTime.ttft": "Tiempo hasta el primer token (TTFT)",
   "duration.seconds": "{seconds}s",
   "duration.minutes": "{minutes}m {seconds}s",
   "command.running": "Ejecutando…",
   "command.failed": "El comando ha fallado",
   "command.done": "Completado",
   "command.title": "Comando",
   "row.running": "Ejecutando",
   "row.failed": "Ha fallado",
   "json.truncated": "… truncado, {total} caracteres en total",
   "clock.md": "{m}/{d}",
   "clock.ymd": "{y}-{m}-{d}",
  },
  "command": {
   "description.compact": "Compactar el historial antiguo de la conversación",
   "description.export": "Descargar el registro de esta sesión como archivo ZIP",
   "description.feedback": "registrar comentarios sobre esta sesión",
   "description.goal": "fijar o ver el objetivo de una tarea larga",
   "description.permission": "Cambiar el preset de permisos (modo de espacio aislado + política de aprobación)",
   "description.plan": "Entrar o salir del modo plan",
   "search.placeholder": "Buscar…",
   "search.aria": "Filtrar opciones",
   "status.loading": "Cargando opciones…",
   "status.applying": "Aplicando…",
   "status.empty": "Sin opciones",
   "overlay.aria": "opciones de /{command}",
   "listbox.aria": "coincidencias de /{command}",
   "notice.attachmentsUnsupported": "/{command} no acepta adjuntos; quítalos primero",
  },
  "common": {
   "ok": "OK",
   "cancel": "Cancelar",
   "close": "Cerrar",
   "copy": "Copiar",
   "copied": "Copiado",
   "copy.failed": "No se pudo copiar",
   "copy.value": "Copiar valor",
   "copy.json": "Copiar JSON",
   "copy.path": "Copiar la ruta de la propiedad",
   "copy.prettyJson": "Copiar JSON formateado",
   "copy.compactJson": "Copiar JSON compacto",
   "copy.optionsHint": "{action}; haz clic derecho para ver las opciones de copia",
   "retry": "Reintentar",
   "loading": "Cargando…",
   "load.failed": "No se pudo cargar",
   "submit": "Enviar",
   "submitting": "Enviando…",
   "next": "Siguiente",
   "previous": "Anterior",
   "skip": "Saltar",
   "delete": "Borrar",
   "edit": "Editar",
   "save": "Guardar",
   "search": "Buscar",
   "more": "Más",
   "collapse": "Contraer",
   "expand": "Expandir",
   "back": "Atrás",
   "brand.localBuild": "Compilación local de DSH",
   "unknown": "Desconocido",
   "none": "Ninguno",
   "truncated": "Truncado",
   "json.collapseNode": "Contraer el nodo JSON",
   "json.expandNode": "Expandir el nodo JSON",
   "json.label": "JSON",
   "markdown.footnotes": "Notas al pie",
   "markdown.truncatedCharacters": "… truncado a {total} caracteres",
   "number.thousand": "{value}K",
   "number.million": "{value}M",
  },
  "conversation": {
   "hint.plan": "describe tu tarea para generar un plan",
   "hint.goal": "describe el objetivo para una tarea larga",
   "hint.goal.active": "objetivo activo — editar / pausar / reanudar / limpiar",
   "placeholder.plan": "describe tu tarea para generar un plan",
   "placeholder.default": "Escribe un mensaje o lanza una tarea, / comandos, @ ficheros o sesiones",
   "placeholder.unavailable": "Sesión no disponible",
   "placeholder.parentOffline": "La sesión madre está desconectada; no se puede enviar, pero sí detener la ejecución",
   "placeholder.hero": "Describe lo que quieres construir, / comandos, @ ficheros o sesiones",
   "placeholder.workspace": "Elige un espacio de trabajo para empezar",
   "placeholder.steerQueue": "Cmd/Ctrl+Enter guía todos los mensajes encolados",
   "input.commands": "Comandos",
   "input.stop": "Detener la generación",
   "input.send": "Enviar mensaje",
   "input.send.queue": "Encolar mensaje",
   "input.send.steer": "Guiar mensaje",
   "input.accessMode": "Modo de acceso, actual: {name}",
   "attachment.pending": "Adjuntos pendientes",
   "attachment.scrollLeft": "Desplazar los adjuntos a la izquierda",
   "attachment.scrollRight": "Desplazar los adjuntos a la derecha",
   "attachment.dropTitle": "Arrastra ficheros o imágenes aquí para añadirlos",
   "attachment.dropDesc": "Límite de imágenes: hasta {count} imágenes, {size} cada una",
   "attachment.dropBlocked": "Ahora mismo no se pueden añadir ficheros ni imágenes",
   "image.pending": "Imágenes pendientes",
   "image.openOriginal": "Ver original",
   "image.openOriginalLabel": "{label}, pulsa para ver el original",
   "image.remove": "Quitar la imagen {name}",
   "image.original": "Imagen original",
   "image.label": "Imagen",
   "image.loadFailed": "La imagen no se ha cargado; pulsa para reintentar",
   "image.loading": "Cargando imagen…",
   "image.preview": "Vista previa de la imagen original",
   "image.closePreview": "Cerrar la vista previa de la imagen original",
   "image.unsupportedType": "Sólo se admiten imágenes PNG, JPG, WebP y GIF",
   "image.tooMany": "Un mensaje puede incluir hasta {count} imágenes",
   "image.fileTooLarge": "Cada imagen debe pesar menos de {size}",
   "image.totalTooLarge": "Las imágenes suman más de {size}; quita algunas y vuelve a intentarlo",
   "image.tooManyPixels": "La resolución de la imagen es demasiado alta; comprímela y vuelve a intentarlo",
   "image.dimensionTooLarge": "Los lados de la imagen deben medir como mucho {size}px; redúcela y vuelve a intentarlo",
   "image.modelUnsupported": "El modelo actual no admite imágenes; cambia a uno que sí lo haga",
   "image.sendFailed": "No se han podido enviar las imágenes ({reason}); vuelve a añadirlas e inténtalo de nuevo",
   "file.attach": "Adjuntar",
   "file.pending": "Ficheros pendientes",
   "file.remove": "Quitar el fichero {name}",
   "file.uploading": "Subiendo…",
   "file.uploadFailed": "La subida ha fallado; pulsa para reintentar",
   "file.retry": "Reintentar la subida de {name}",
   "file.stillUploading": "Los ficheros se están subiendo todavía; envía cuando terminen",
   "file.sessionUnavailable": "Sesión no disponible; no se pueden subir ficheros",
   "file.notStaged": "El fichero no ha terminado de subirse; vuelve a añadirlo e inténtalo de nuevo",
   "file.label": "Fichero",
   "context.aria": "{percent} del contexto usado",
   "context.used": "del contexto usado",
   "context.system": "Prompt del sistema",
   "context.tools": "Definiciones de herramientas",
   "context.messages": "Mensajes",
   "settings.enter.title": "Qué hacen Enter y el botón Enviar mientras trabaja",
   "settings.enter.description": "Qué hacen Enter y el botón Enviar mientras el agente está en marcha; Cmd/Ctrl+Enter usa el otro comportamiento",
   "settings.enter.queue": "Encolar",
   "settings.enter.steer": "Guiar",
   "access.preset.readOnly": "Sólo mirar",
   "access.preset.workspaceWrite": "Dentro del taller",
   "access.preset.fullAccess": "A rienda suelta",
   "access.confirm.title": "¿Activar A rienda suelta?",
   "access.confirm.description": "A rienda suelta reduce los pasos de confirmación y deja que el agente haga más acciones por su cuenta, incluidas operaciones delicadas, cambios en ficheros o comandos externos. Úsalo sólo cuando te fíes de la tarea en curso.",
   "access.confirm.acknowledge": "Entiendo los riesgos y quiero continuar",
   "access.confirm.cancel": "Cancelar",
   "access.confirm.enable": "Activar A rienda suelta",
   "hero.headline": "Hacia lo desconocido",
   "hero.preview": "Vista previa",
   "hero.chooseWorkspace": "Elegir espacio de trabajo",
   "session.hierarchy": "Jerarquía de sesiones",
   "todo.title": "Tareas pendientes",
   "todo.progress.done": "{done} completadas",
   "todo.progress.active": "{active} en curso",
   "todo.progress.pending": "{pending} pendientes",
   "todo.rowTitle": "Actualizar la lista de tareas",
   "todo.completed": "{done}/{total} completadas",
   "command.attachmentsUnsupported": "/{command} no acepta adjuntos; quítalos primero",
   "ask.rowTitle": "Hacer una pregunta",
   "ask.waiting": "en espera",
   "ask.cancelled": "cancelada",
   "ask.cancelledDetail": "Este conjunto de preguntas se canceló antes de enviar las respuestas.",
   "ask.interrupted": "interrumpida",
   "ask.interruptedDetail": "Este conjunto de preguntas se interrumpió antes de enviar las respuestas.",
   "ask.answered": "{answered}/{total} respondidas",
   "ask.skipped": "Sin responder",
   "bash.running": "En marcha",
   "bash.failed": "Falló",
   "bash.stopped": "Detenido",
   "row.running": "En marcha",
   "row.failed": "Falló",
   "row.stopped": "Detenido",
   "row.input": "IN",
   "row.output": "OUT",
   "row.inspect": "Inspeccionar",
   "tool.title.search": "Búsqueda",
   "tool.title.read": "Lectura",
   "tool.title.bash": "Bash",
   "tool.title.write": "Escritura",
   "tool.title.edit": "Edición",
   "tool.title.code": "Código",
   "tool.title.generic": "Llamada a herramienta",
   "tool.title.inspect": "Inspeccionar",
   "tool.title.runCordis": "Ejecutar plugin Cordis",
   "tool.title.stopCordis": "Detener plugin Cordis",
   "tool.title.removeCordis": "Quitar plugin Cordis",
   "tool.title.pwsh": "Pwsh",
   "tool.title.readImage": "Leer imagen",
   "tool.title.grep": "Grep",
   "tool.title.glob": "Glob",
   "tool.title.webSearch": "Búsqueda",
   "tool.title.webFetch": "Descarga",
   "diff.files.one": "{count} fichero",
   "diff.files.other": "{count} ficheros",
   "diff.collapseAria": "Contraer el diff",
   "diff.expandAria": "Desplegar {count} líneas de diff más",
   "diff.expandRest": "… {count} líneas más",
   "read.window": "Mostrando {shown} de {total} líneas",
   "read.collapseAria": "Contraer el contenido",
   "read.expandAria": "Desplegar {count} líneas más",
   "read.expandRest": "… {count} líneas más",
   "search.paths": "{shown} rutas",
   "search.paths.truncated": "Mostrando {shown} de {total} rutas",
   "search.matches": "{shown} coincidencias · {files} ficheros",
   "search.matches.truncated": "Mostrando {shown} de {total} coincidencias · {files} ficheros",
   "search.noResults": "Sin resultados",
   "search.collapseAria": "Contraer los resultados",
   "search.expandAria": "Desplegar {count} líneas de resultado más",
   "search.expandRest": "… {count} líneas más",
   "web.noResults": "No se han encontrado resultados",
   "web.sourcesTruncated": "Lista de fuentes recortada",
   "web.http": "HTTP",
   "web.contentTruncated": "Contenido recortado",
   "details.running": "En marcha…",
   "queue.count": "{n} mensajes encolados",
   "queue.sending": "Enviando…",
   "queue.image": "Imagen del mensaje encolado",
   "queue.file": "Fichero encolado {name}",
   "queue.edit": "Editar el mensaje encolado",
   "queue.edit.unsupported": "Contiene contenido que no es texto; editarlo aún no está soportado",
   "queue.save": "Guardar el mensaje encolado",
   "queue.cancelEdit": "Cancelar la edición",
   "queue.remove": "Quitar el mensaje encolado",
   "queue.steer": "Guiar el mensaje encolado",
   "queue.steer.unavailable": "Guiar sólo está disponible mientras el agente está en marcha",
   "queue.editFailed": "La edición ha fallado: puede que este mensaje ya haya empezado a enviarse.",
   "queue.removeFailed": "No se ha podido quitar: puede que este mensaje ya haya empezado a enviarse.",
   "queue.steerFailed": "No se ha podido guiar. Inténtalo de nuevo.",
   "terminal.signal": "señal {signal}",
   "terminal.exitCode": "código de salida {code}",
   "terminal.running": "En marcha",
   "terminal.failed": "Falló",
   "terminal.done": "Terminado",
   "terminal.noOutput": "Sin salida",
   "terminal.collapseAria": "Contraer la salida",
   "terminal.expandAria": "Desplegar las {n} líneas de salida restantes",
   "terminal.expandRest": "… {n} líneas más",
   "terminal.sendInput": "(enviar entrada)",
   "terminal.session": "Terminal {sessionId}",
  },
  "cordis": {
   "row.defineTitle": "Registrar plugin de Cordis",
   "row.runTitle": "Ejecutar plugin de Cordis",
   "row.updateTitle": "Actualizar plugin de Cordis",
   "row.stopTitle": "Parar plugin de Cordis",
   "row.removeTitle": "Quitar plugin de Cordis",
   "purpose.missing": "(sin propósito indicado)",
   "status.idle": "Listo",
   "status.awaitingApproval": "Esperando aprobación",
   "status.failed": "La ejecución falló",
   "status.clientPending": "Cliente listo para activarse",
   "status.running": "En marcha",
   "status.removed": "Quitado",
   "status.superseded": "Hay una ejecución más reciente",
   "run.removed": "Este paquete ya no existe",
   "run.superseded": "Abajo hay una tarjeta de ejecución más reciente",
   "panel.hint": "Los controles de ejecución están en el panel de Cordis, encima de Ajustes",
   "panel.plugins.aria": "Plugins de Cordis",
   "panel.approvals.aria": "Aprobaciones de Cordis",
   "panel.trigger": "Plugin de Cordis",
   "panel.runningCount": "{count} en marcha",
   "panel.title": "Plugins de Cordis",
   "panel.empty": "Todavía no hay plugins definidos",
   "panel.loading": "Leyendo…",
   "panel.readFailed": "No se pudo leer el inventario de plugins: {message}",
   "panel.group.current": "Esta sesión",
   "panel.group.others": "Otras sesiones",
   "panel.version": "Versión",
   "panel.current": "Actual: {packageId}",
   "panel.next": "Siguiente: {packageId}",
   "action.approve": "Permitir",
   "action.approveOnce": "Permitir sólo esta versión",
   "action.approvePlugin": "Permitir futuras versiones de este plugin",
   "action.decline": "Rechazar",
   "action.run": "Ejecutar",
   "action.stop": "Parar",
   "action.remove": "Quitar",
   "action.retry": "Reintentar",
   "action.rollback": "Revertir",
   "action.inspect": "Inspeccionar",
   "render.failedAbdicated": "Falló el dibujado en {slot}; se ha restaurado la interfaz por defecto:",
   "render.failedHeld": "Falló el dibujado en {slot}:",
   "a11y.defining": "Definiendo el plugin",
   "a11y.failed": "Falló la definición",
   "a11y.stopped": "Definición interrumpida",
   "body.source": "Código fuente del plugin",
   "body.hostCode": "Host",
   "body.clientCode": "Cliente",
   "body.output": "Resultado",
   "body.copy": "Copiar",
   "body.copied": "Copiado",
  },
  "deliverables": {
   "presented.nativeUnavailable": "Este fichero no tiene una ruta de Host disponible. Previsualízalo en la barra lateral.",
   "presented.revealError": "No se pudo mostrar en el gestor de ficheros. Inténtalo de nuevo.",
   "presented.directoryError": "No se pudo abrir la carpeta contenedora. Inténtalo de nuevo.",
   "presented.directoryOpening": "Abriendo la carpeta contenedora…",
   "presented.directoryOpened": "Se pidió abrir la carpeta contenedora",
   "presented.revealed": "Se pidió mostrar en el gestor de ficheros",
   "presented.revealing": "Mostrando en el gestor de ficheros…",
   "presented.unavailable": "Este Host no tiene escritorio disponible para abrir ficheros ni carpetas",
   "presented.retry": "Reintentar",
   "presented.hostError": "No se pudo leer la información del escritorio del Host",
   "presented.directory": "Abrir la carpeta contenedora",
   "presented.explorer": "Mostrar en el Explorador de archivos",
   "presented.finder": "Mostrar en el Finder",
   "presented.defaultApp": "Abrir con la aplicación por defecto",
   "presented.more": "Más acciones de fichero para {name}",
   "presented.action": "Abrir",
   "presented.preview": "Previsualizar en la barra lateral",
   "presented.previewButton": "Abrir {name} en la barra lateral",
   "presented.previewCard": "Previsualizar {name} en la barra lateral",
   "presented.all": "Los {count} ficheros",
   "presented.expandAria": "Mostrar los {count} ficheros entregados",
   "presented.collapse": "Contraer",
   "presented.collapseAria": "Contraer los ficheros entregados",
   "presented.opening": "Abriendo…",
   "presented.opened": "Abierto con la aplicación por defecto",
   "presented.error": "No se pudo abrir. Haz clic para reintentar.",
   "presented.file": "Fichero",
   "row.title": "Presentar ficheros",
   "row.running": "Entregando",
   "row.ok": "Entregado",
   "row.error": "Fallo en la entrega",
   "row.stopped": "Interrumpido",
   "row.inspect": "Inspeccionar la llamada",
   "presented.open": "Abrir {name} con la aplicación por defecto",
   "produced.label": "Ficheros modificados",
   "produced.moreOne": "+ 1 fichero",
   "produced.more": "+ {count} ficheros",
   "produced.open": "Abrir {name}",
  },
  "documentHtml": {
   "title": "HTML",
   "frame": "Vista previa del documento HTML",
   "loading": "Preparando la vista previa del HTML…",
   "failed": "No se pudo previsualizar este documento HTML.",
  },
  "documentMarkdown": {
   "viewer.label": "Markdown",
   "code.copy": "Copiar",
   "code.copied": "Copiado",
   "footnotes": "Notas al pie",
  },
  "feedback": {
   "action.like": "Buena respuesta",
   "action.likeActive": "Quitar valoración",
   "action.dislike": "Mala respuesta",
   "action.dislikeActive": "Quitar valoración",
   "dialog.title": "Enviar comentarios",
   "dialog.categories": "Categoría de los comentarios",
   "dialog.detail": "Detalles de los comentarios",
   "dialog.hint": "Añade detalles para ayudarnos a mejorar. Tu envío incluirá el registro de la conversación actual.",
   "category.task-result": "Resultado de la tarea",
   "category.instruction-following": "Comprensión y seguimiento de las instrucciones",
   "category.product-interaction": "Funciones del producto e interacción",
   "category.service-stability": "Estabilidad y velocidad",
   "category.resource-cost": "Uso de recursos y coste",
   "category.security-privacy-permission": "Seguridad, privacidad y permisos",
   "category.other": "Otro",
   "toast.recorded": "Gracias por tus comentarios",
   "error.conflict": "Estos comentarios cambiaron en otro sitio; se muestra el estado más reciente",
   "error.load": "No se pudieron cargar los comentarios",
   "error.generic": "No se pudieron guardar los comentarios",
   "error.noteTooLarge": "La descripción es demasiado larga; acórtala y vuelve a enviarla",
  },
  "goal": {
   "phase.active": "Objetivo en curso",
   "phase.active.disarmed": "Objetivo inactivo",
   "phase.paused": "Objetivo en pausa",
   "phase.blocked": "Objetivo bloqueado",
   "objective.aria": "Campo de objetivo",
   "commandInput.aria": "Entrada de comandos",
   "action.save": "Guardar objetivo",
   "action.cancel": "Cancelar edición",
   "action.pause": "Pausar objetivo",
   "action.resume": "Reanudar objetivo",
   "action.edit": "Editar objetivo",
   "action.clear": "Borrar objetivo",
  },
  "job": {
   "count.live.one": "{count} trabajo en segundo plano en marcha",
   "count.live.other": "{count} trabajos en segundo plano en marcha",
   "count.idle.one": "{count} trabajo en segundo plano",
   "count.idle.other": "{count} trabajos en segundo plano",
   "list.aria": "Trabajos en segundo plano",
   "status.running": "en marcha",
   "status.stopping": "parando",
   "status.completed": "completado",
   "status.killed": "cancelado",
   "status.failed": "fallido",
   "duration.seconds": "{seconds}s",
   "duration.minutes": "{minutes}m {seconds}s",
   "duration.hours": "{hours}h {minutes}m",
   "duration.title.live": "En marcha desde hace {duration}",
   "duration.title.done": "Tardó {duration}",
  },
  "model": {
   "command.description": "Elegir el modelo de esta conversación",
   "option.loadError": "No se pudo cargar el catálogo: {message}",
   "option.deepseekV4Flash.description": "Rápido, eficiente y económico; va bien para tareas concretas, rutinarias o en paralelo.",
   "option.deepseekV4Pro.description": "Más sólido en programación con agente, conocimiento y razonamiento difícil; va bien para tareas complejas o donde la calidad es crítica, con mayor coste.",
   "trigger.fallback": "Elegir modelo",
   "trigger.loading": "Cargando modelos…",
   "trigger.selectAria": "Elegir modelo",
   "trigger.aria": "Elegir modelo, actual {model}",
   "trigger.ariaEffort": "Elegir modelo, actual {model}, esfuerzo de razonamiento {effort}",
   "menu.aria": "Modelo y esfuerzo de razonamiento",
   "menu.model": "Modelo",
   "menu.effort": "Esfuerzo",
   "effort.providerDefault": "Por defecto",
   "status.loading": "Actualizando la lista de modelos…",
   "error.action": "La operación con el modelo falló: {message}",
   "action.reload": "Recargar",
   "warning.groupLoad": "No se pudo cargar {name}: {message}",
   "empty.models": "No hay modelos disponibles.",
   "blocked.composer": "Este modelo no está disponible — elige otro para continuar",
   "empty.efforts": "Este modelo no ofrece niveles de esfuerzo de razonamiento.",
  },
  "open-in-app": {
   "open.title": "Abrir espacio de trabajo en {app}",
   "open.tooltip": "Abrir en local",
   "open.error": "No se pudo abrir",
   "menu.toggle": "Elige en qué aplicación abrir",
   "menu.aria": "Abrir en",
   "app.cursor": "Cursor",
   "app.vscode": "VS Code",
   "app.vscodeinsiders": "VS Code Insiders",
   "app.windsurf": "Windsurf",
   "app.zed": "Zed",
   "app.sublimetext": "Sublime Text",
   "app.xcode": "Xcode",
   "app.androidstudio": "Android Studio",
   "app.intellij": "IntelliJ IDEA",
   "app.pycharm": "PyCharm",
   "app.webstorm": "WebStorm",
   "app.phpstorm": "PhpStorm",
   "app.goland": "GoLand",
   "app.rider": "Rider",
   "app.rustrover": "RustRover",
   "app.fork": "Fork",
   "app.sourcetree": "Sourcetree",
   "app.github": "GitHub Desktop",
   "app.tower": "Tower",
   "app.gitkraken": "GitKraken",
   "app.smartgit": "SmartGit",
   "app.sublimemerge": "Sublime Merge",
   "app.ghostty": "Ghostty",
   "app.warp": "Warp",
   "app.iterm": "iTerm2",
   "app.kitty": "kitty",
   "app.windowsterminal": "Windows Terminal",
   "app.gitbash": "Git Bash",
   "app.gnometerminal": "GNOME Terminal",
   "app.konsole": "Konsole",
   "app.finder": "Finder",
   "app.explorer": "Explorador de ficheros",
   "app.filemanager": "Archivos",
   "app.terminal": "Terminal",
  },
  "plan": {
   "chip.label": "Plan",
   "chip.on.aria": "Modo plan activado, pulsa para desactivarlo",
   "chip.on.title": "Modo plan activado — haz clic para desactivarlo (/plan off)",
   "chip.off.aria": "Modo plan desactivado, pulsa para activarlo",
   "chip.off.title": "Modo plan desactivado — haz clic para activarlo (/plan)",
   "chip.exitFailed": "No se pudo salir del modo plan",
  },
  "question": {
   "error.incomplete": "Completa esta pregunta primero.",
   "error.unanswered": "Elige una opción o escribe una respuesta propia.",
   "nav.prev": "Pregunta anterior",
   "nav.next": "Pregunta siguiente",
   "nav.minimize": "Plegar la tarjeta de la pregunta",
   "nav.maximize": "Desplegar la tarjeta de la pregunta",
   "nav.cancel": "Descartar todas las preguntas",
   "option.recommended": "Recomendada",
   "custom.placeholder": "Escribe tu respuesta",
   "action.skip": "Saltar esta pregunta",
   "action.next": "Siguiente",
   "plan.header": "Revisión del plan",
   "plan.approve": "Aprobar",
   "plan.decline": "Rechazar",
   "plan.discuss": "Hablar de ello",
  },
  "reference": {
   "section.files": "Ficheros y carpetas",
   "section.sessions": "Sesiones",
   "candidate.noCwd": "(sin cwd)",
   "crumb.root": "Espacio de trabajo",
   "time.now": "ahora",
   "time.minutes": "{n}min",
   "time.hours": "{n}h",
   "time.days": "{n}d",
   "time.months": "{n}mes",
   "time.years": "{n}a",
  },
  "schedule.catalog": {
   "trigger.one": "{count} recordatorio",
   "trigger.other": "{count} recordatorios",
   "list.aria": "Recordatorios activos",
   "status.scheduled": "Programado",
   "status.overdue": "Atrasado",
   "frequency.once": "Una vez",
   "frequency.every": "Cada {value} {unit}",
   "unit.day.one": "día",
   "unit.day.other": "días",
   "unit.hour.one": "hora",
   "unit.hour.other": "horas",
   "unit.minute.one": "minuto",
   "unit.minute.other": "minutos",
   "unit.second.one": "segundo",
   "unit.second.other": "segundos",
   "relative.now": "Vence ahora",
   "relative.future": "dentro de {value} {unit}",
   "relative.overdue": "{value} {unit} de retraso",
  },
  "session-log-download": {
   "header.more": "Más acciones",
   "menu.download": "Descargar el registro de la sesión",
   "dialog.preparingTitle": "Exportando la sesión",
   "dialog.preparingDescription": "Preparando un ZIP que contiene esta sesión, sus subsesiones y sus adjuntos.",
   "dialog.successTitle": "Descarga de la sesión iniciada",
   "dialog.successDescription": "El navegador está descargando el ZIP de la sesión.",
   "dialog.errorTitle": "Falló la exportación de la sesión",
   "dialog.close": "Cerrar",
   "dialog.commandFailed": "No se pudo iniciar la exportación de la sesión.",
  },
  "settings": {
   "trigger": "Ajustes",
   "title": "Ajustes",
   "close": "Cerrar",
   "openDocument": "Abrir fichero de configuración",
   "openDocument.error": "No se pudo abrir el fichero de configuración",
   "general.nav": "General",
   "connection.error": "Sin conexión",
   "connection.retry": "Reconectar ahora",
   "connection.connecting": "Reconectando",
   "connection.connected": "Conectado",
   "connection.reconnect": "Sin conexión, reconecta ahora",
   "connection.restart": "Reconectando automáticamente, reconecta ahora",
  },
  "settings.agentPreset": {
   "error": "No se pudieron cargar los presets de agente.",
   "userTrust": "Personalizado",
   "seatHint": "Preset de agente para la sesión que vas a empezar",
   "headerHint": "El preset de agente con el que corre esta sesión, fijado cuando arrancó",
   "nav": "Presets de agente",
   "sectionIntro": "Un preset es la composición de plugins con la que corre el agente de una sesión — sus herramientas, sus instrucciones y sus capacidades. Duplica uno de los que ya existen y hazlo tuyo, o deja que el agente te lo redacte en el modo creador.",
   "builtIn": "De serie",
   "setDefault": "Poner por defecto",
   "view": "Ver",
   "presetStandardName": "Modo estándar",
   "presetStandardDescription": "Agente de programación completo con edición de ficheros, shell, búsqueda de ficheros y en la web, skills, planificación, objetivos, subagentes y flujos de trabajo.",
   "presetPtcName": "Modo PTC",
   "presetPtcDescription": "Agente de programación completo sin la herramienta de flujos de trabajo; el resto de herramientas se exponen a través del SDK del modo PTC para que el modelo pueda combinar operaciones de varios pasos en un solo programa TypeScript.",
   "presetMinimalName": "Modo mínimo",
   "presetMinimalDescription": "Agente de programación de una sola herramienta con un shell persistente.",
   "presetCordisName": "Modo creador",
   "presetCordisDescription": "Pensado para crear presets de agente personalizados: trae todo lo del modo estándar y además inspección en tiempo de ejecución, experimentos con plugins y guía para escribir presets.",
   "duplicate": "Duplicar",
   "duplicateUnavailable": "Esta instalación no tiene ninguna carpeta de presets en la que se pueda escribir",
   "delete": "Borrar",
   "presetId": "Identificador",
   "presetIdPlaceholder": "mi-agente",
   "displayName": "Nombre",
   "displayNamePlaceholder": "Se muestra en el selector; por defecto es el identificador",
   "inUse": "En uso",
   "builtInGroup": "De serie",
   "customGroup": "Personalizado",
   "noDescription": "Sin descripción.",
   "brokenBadge": "No se pudo cargar",
   "brokenNoCopy": "Un preset que no se pudo cargar no se puede duplicar",
   "switchRefused": "No se pudo cambiar a {name}: {reason}",
   "copyOf": "Copiado de",
   "composition": "Composición (agent.cordis.yml)",
   "cancel": "Cancelar",
   "close": "Cerrar",
   "retry": "Reintentar",
   "copyTitle": "Duplicar preset",
   "copyIntro": "El preset entero se copia en esta máquina. El identificador pasa a ser el nombre de su carpeta y no se puede cambiar después; todo lo demás se edita en los ficheros del propio preset.",
   "create": "Crear",
   "creating": "Creando…",
   "creatorDraft": "Redactar un preset personalizado con el modo creador",
   "openLocation": "Abrir carpeta",
   "showLocation": "Mostrar ubicación",
   "revealedPathLabel": "Ficheros del preset:",
   "idRequired": "Ponle un identificador al preset.",
   "idInvalid": "Usa letras minúsculas, dígitos y guiones, empezando por una letra o un dígito.",
   "idTaken": "Ya existe un preset con este identificador.",
   "deleteTitle": "¿Borrar este preset?",
   "deleteDescription": "Se borra la carpeta del preset. Las sesiones que ya están corriendo con él siguen funcionando; las sesiones nuevas no podrán elegirlo.",
   "deleteConfirm": "Borrar",
   "deleting": "Borrando…",
  },
  "settings.locale": {
   "language.title": "Idioma",
  },
  "settings.models": {
   "nav": "Modelos",
   "title": "Modelos",
   "intro": "Introduce tus claves de API para usar modelos de los siguientes proveedores.",
   "edit": "Editar",
   "editProvider": "Editar {provider}",
   "remove": "Borrar",
   "removeProvider": "Borrar {provider}",
   "deleteTitle": "¿Borrar {provider}?",
   "deleteDescription": "Borrar {provider} elimina su configuración. Cualquier credencial que use se gestiona en otro sitio y se conservará.",
   "deleteDescriptionWithCredential": "Borrar {provider} elimina su configuración y su clave de API guardada.",
   "deleteConfirm": "Borrar {provider}",
   "deleting": "Borrando {provider}…",
   "add": "Añadir proveedor",
   "provider": "Proveedor",
   "close": "Cerrar",
   "cancel": "Cancelar",
   "apply": "Aplicar",
   "applying": "Aplicando…",
   "savedProvider": "Guardado {provider}.",
   "credentialConfigured": "Clave de API configurada",
   "credentialMissing": "Falta la clave de API",
   "readOnly": "El documento de ajustes es de sólo lectura en este despliegue.",
   "loadFailed": "No se pudo cargar el directorio de proveedores",
   "conflict": "Alguien ha cambiado estos ajustes mientras esta tarjeta estaba abierta. Ciérrala y vuelve a abrirla para editar los valores actuales.",
   "retry": "Reintentar",
   "keyInput": "Clave de API",
   "keyPlaceholder": "Introduce tu clave de API",
   "keyPlaceholderNative": "Introduce una clave de API, o déjalo en blanco para usar la autenticación del entorno",
   "keyStored": "Configurada — introduce un valor nuevo para reemplazarla",
   "keyEnvLocked": "La aporta el entorno de arranque (sólo lectura)",
   "customized": "Ajustes personalizados",
   "baseUrl": "URL base",
   "baseUrlDefault": "Por defecto del proveedor",
   "models": "Modelos",
   "modelsInherited": "Usando los valores por defecto del adaptador",
   "modelsCustomized": "Catálogo de modelos personalizado",
   "resetModels": "Restaurar valores por defecto",
   "model": "Modelo",
   "modelId": "ID del modelo",
   "modelName": "Nombre visible",
   "modelNamePlaceholder": "Usa el ID del modelo cuando está vacío",
   "contextWindow": "Ventana de contexto",
   "contextWindowPlaceholder": "Usa el valor por defecto del proveedor",
   "maxTokens": "Tokens máximos de salida",
   "maxTokensPlaceholder": "Usa el valor por defecto del proveedor",
   "modelAdvanced": "Capacidades",
   "addModel": "Añadir modelo",
   "removeModel": "Borrar modelo",
   "modelsEmpty": "No se mostrará ningún modelo en el selector. Los ID que no estén en la lista se pueden enviar igualmente de forma directa.",
   "keyBlank": "Introduce la clave de API, o deja el campo vacío para conservar la guardada.",
   "keyBlankNew": "Introduce la clave de API, o deja el campo vacío si este proveedor se autentica de otra forma.",
   "keyIllegalCharacters": "Esta clave de API no tiene un formato válido. Compruébala.",
   "modelIdRequired": "El ID del modelo es obligatorio.",
   "modelIdDuplicate": "El ID del modelo tiene que ser único.",
   "modelNameInvalid": "El nombre visible no puede estar vacío.",
   "modelContextInvalid": "La ventana de contexto tiene que ser un número positivo, como 131072, 256K o 1M.",
   "modelMaxTokensInvalid": "Los tokens máximos de salida tienen que ser un número positivo, como 8192, 64K o 1M.",
   "advancedHint": "Los demás campos están en settings.yaml; edita esa sección directamente.",
   "modelCapacityInvalid": "Una capacidad tiene que ser un número, con el sufijo K o M si quieres.",
   "modelDuplicate": "Cada ID de modelo sólo puede aparecer una vez.",
   "modelContextWindow": "Ventana de contexto",
   "modelMaxTokens": "Tokens máximos de salida",
   "fetchModels": "Buscar modelos disponibles",
   "fetching": "Preguntando al proveedor…",
   "fetchNeedsBaseUrl": "Introduce antes la URL base, y luego busca.",
   "fetchEmpty": "El proveedor no listó ningún modelo. Añádelos a mano.",
   "fetchTitle": "Elige los modelos que añadir",
   "fetchDescription": "Estos son los modelos que tiene disponibles este proveedor. Elige los que quieras añadir.",
   "fetchSearch": "Buscar modelos",
   "fetchNoMatches": "Ningún modelo coincide.",
   "fetchSelectAll": "Seleccionar todo",
   "fetchDeselectAll": "Deseleccionar todo",
   "fetchAdopt": "Añadir seleccionados",
   "customAdd": "Añadir un proveedor personalizado",
   "customTitle": "Proveedor personalizado",
   "customTag": "Personalizado",
   "customRoute": "ID del proveedor",
   "customRouteHint": "Identificador en minúsculas, que empieza por letra, y que nombra este proveedor de forma única en las peticiones y como nombre de su credencial.",
   "customRouteInvalid": "Empieza por una letra minúscula; después, letras minúsculas, dígitos y guiones.",
   "customRouteTaken": "Ya hay un proveedor que usa este ID.",
   "customDisplayName": "Nombre visible",
   "customApi": "Protocolo de API",
   "customApiUnset": "Sin seleccionar",
   "customNeedsBaseUrl": "Un proveedor personalizado necesita una URL base.",
   "customBaseUrlInvalid": "Introduce una URL HTTP o HTTPS válida.",
   "customNeedsModels": "Un proveedor personalizado necesita al menos un modelo.",
   "customBaseUrlPlaceholder": "https://gateway.example/v1",
   "settingsPathUnresolvable": "ruta de ajustes no resoluble",
   "create": "Crear proveedor",
   "creating": "Creando…",
   "welcomeTitle": "Aviso de pruebas internas",
   "welcomeBody": "DeepSeek Harness 0.1 sigue en pruebas para los desarrolladores de Harness. Todavía hay muchas áreas por mejorar, y agradecemos los comentarios de la comunidad de desarrolladores. Los plugins principales y las API básicas de DeepSeek Harness seguirán evolucionando muy rápido en los próximos meses.\n\nTenemos ganas de explorar los límites de la inteligencia con desarrolladores de todo el mundo, apoyándonos en una infraestructura de código abierto, abierta, reutilizable y componible. Invitamos a los desarrolladores de Harness de todas partes a sumarse al ecosistema de plugins de DSH.",
   "welcomeContinue": "Continuar",
   "welcomeError": "No se pudo guardar la confirmación. Inténtalo de nuevo.",
   "onboardingTitle": "Añade una clave de API para empezar",
   "onboardingDescription": "Configura el proveedor oficial de DeepSeek para empezar a construir.",
   "onboardingLater": "Configurar más tarde",
   "onboardingSave": "Guardar y continuar",
   "onboardingSaving": "Guardando…",
   "keyRequired": "Introduce una clave de API para continuar.",
  },
  "settings.permission": {
   "title": "Permiso",
   "description": "Elige el modo de permiso por defecto para las sesiones nuevas",
   "loading": "Cargando",
   "unavailable": "No disponible",
   "preset.readOnly": "Sólo mirar",
   "preset.workspaceWrite": "Dentro del taller",
   "preset.fullAccess": "A rienda suelta",
   "confirm.title": "¿Activar A rienda suelta?",
   "confirm.description": "A rienda suelta permite que las sesiones nuevas recorten los pasos de confirmación y hagan más acciones directamente, incluidas operaciones sensibles, cambios en ficheros o comandos externos. Úsalo sólo cuando te fíes de las tareas que vengan después.",
   "confirm.acknowledge": "Entiendo los riesgos y quiero continuar",
   "confirm.cancel": "Cancelar",
   "confirm.enable": "Activar A rienda suelta",
  },
  "settings.pluginInventory": {
   "tab": "Lista de plugins",
   "loading": "Leyendo plugins…",
   "error": "Los plugins no están disponibles de momento.",
   "retry": "Reintentar",
   "search": "Buscar plugins",
   "empty": "No hay plugins disponibles.",
   "emptySearch": "Ningún plugin coincide.",
   "presetTitle": "Plugins de la sesión",
   "presetSubtitle": "Los presets de agente los componen en cada sesión",
   "countUnit": "plugins",
   "switcherLabel": "Elige el preset de agente que quieres inspeccionar",
   "presetOptionDefault": "{name} (por defecto)",
   "presetOptionBroken": "{name} (no se pudo cargar)",
   "globalTitle": "Plugins globales",
   "globalSubtitle": "Compartidos por el sistema y todas las sesiones",
   "presetProvidedDetail": "Desactivado en global; los presets de agente lo aportan en cada sesión",
   "enabledIn": "Activado en",
   "viewInPreset": "Ver en el grupo del preset",
   "matchesInOtherPresets": "{count} coincidencias más en otros presets: ",
   "failedCountLabel": "fallidos",
   "enabledTag": "Activado",
   "disabledTag": "Desactivado",
   "conditionalTag": "Condicional",
   "presetEnabledTag": "Activado por presets",
   "failedTag": "Falló",
   "moduleLabel": "Módulo",
   "fromPreset": "De",
   "condition": "Se desactiva cuando",
   "configuration": "Configuración",
   "runtime": "Estado",
   "unobserved": "No está en marcha",
   "pending": "Esperando dependencias",
   "loadingPhase": "Cargando",
   "active": "En marcha",
   "failed": "No arrancó",
   "unloading": "Descargando",
  },
  "settings.plugins": {
   "nav": "Plugins",
   "title": "Plugins",
   "intro": "Configura e inspecciona los plugins instalados en este despliegue.",
   "tabs": "Vistas de plugins",
   "configurableTab": "Configuración del plugin",
   "empty": "Este despliegue no expone ningún ajuste de plugin.",
   "overridden": "Modificado",
   "reset": "Restaurar valor por defecto",
   "readOnly": "Este despliegue guarda los ajustes en modo de sólo lectura.",
   "expand": "Ver ajustes",
   "collapse": "Ocultar ajustes",
   "save": "Guardar",
   "saving": "Guardando…",
   "discard": "Descartar",
   "unsaved": "Sin guardar",
   "saveFailed": "El despliegue no aceptó estos valores; los dejamos para que los corrijas.",
   "invalidNumber": "Escribe un número, o déjalo en blanco para usar el valor por defecto.",
   "bashTitle": "Shell",
   "bashDescription": "Limita todos los comandos que ejecuta el agente.",
   "bashTimeoutMs": "Tiempo de espera del comando (ms)",
   "bashTimeoutMsHint": "Cuánto puede durar un comando antes de que se corte.",
   "bashMaxOutputBytes": "Límite de salida por flujo (bytes)",
   "bashMaxOutputBytesHint": "La salida que supere este límite va a un fichero temporal en vez de perderse.",
   "agentLoopTitle": "Bucle del agente",
   "agentLoopDescription": "Cómo reparte el agente las llamadas a herramienta.",
   "agentLoopMaxParallel": "Llamadas a herramienta en paralelo",
   "agentLoopMaxParallelHint": "Tope de llamadas seguras en paralelo que pueden correr a la vez dentro de un paso.",
   "webSearchTitle": "Búsqueda web",
   "webSearchDescription": "El proveedor de búsqueda de DeepSeek.",
   "webSearchApiKey": "Clave de API",
   "webSearchApiKeyHint": "Se guarda fuera del fichero de ajustes. Déjalo en blanco para conservar la clave actual.",
   "webSearchApiKeySet": "Hay una clave configurada.",
   "webSearchApiKeyUnset": "No hay ninguna clave configurada; la búsqueda no estará disponible hasta que la haya.",
   "webSearchBaseUrl": "Dirección base",
   "webSearchBaseUrlHint": "Déjalo en blanco para usar el valor por defecto del proveedor.",
   "webSearchMaxUses": "Búsquedas máximas por petición",
   "webSearchMaxUsesHint": "Cuántas veces puede buscar una petición antes de tener que responder.",
   "subagentModelSelectionTitle": "Subagente",
   "subagentModelSelectionDescription": "Controla qué modelos pueden elegir los agentes para los subagentes.",
   "subagentModelSelectionToggle": "Permitir que los agentes elijan modelos para los subagentes",
   "subagentModelSelectionChoose": "Con esto activado, los agentes pueden elegir proveedor, modelo y esfuerzo de razonamiento para cada subagente entre los modelos autorizados de abajo. Sólo se aplica a las sesiones nuevas.",
   "subagentModelSelectionAllowed": "Modelos que pueden elegir los agentes",
   "subagentModelSelectionLoading": "Cargando modelos…",
   "subagentModelSelectionLoadFailed": "No se pudieron cargar los modelos.",
   "subagentModelSelectionRetry": "Reintentar",
   "subagentModelSelectionPartial": "Algunos proveedores de modelos no se pudieron cargar; las elecciones guardadas se pueden seguir quitando.",
   "subagentModelSelectionUnavailable": "No disponible ahora mismo",
   "subagentModelSelectionUnavailableGroup": "Guardado pero no disponible ahora mismo",
   "subagentModelSelectionEmpty": "Ahora mismo ningún proveedor de modelos ofrece ningún modelo.",
   "subagentModelSelectionRequired": "Elige al menos un modelo antes de guardar.",
   "subagentModelSelectionConflict": "Los ajustes han cambiado en otro sitio. Descarta el borrador y vuelve a intentarlo.",
   "subagentModelSelectionOff": "Los subagentes usan los valores por defecto configurados o heredan el modelo del agente padre. Las elecciones de modelo guardadas se conservan.",
  },
  "settings.theme": {
   "appearance.title": "Aspecto",
   "appearance.light": "Claro",
   "appearance.dark": "Oscuro",
   "appearance.system": "Sistema",
   "fontSize.title": "Tamaño de letra",
   "fontSize.description": "Sólo afecta al contenido de la conversación",
   "fontSize.unit": "px",
   "fontSize.increase": "Aumentar el tamaño de letra",
   "fontSize.decrease": "Reducir el tamaño de letra",
  },
  "sidebar": {
   "session.new": "Nueva sesión",
   "session.new.label": "Nueva sesión",
   "toggle.open": "Abrir barra lateral",
   "toggle.collapse": "Contraer barra lateral",
   "panels.label": "Paneles globales",
  },
  "sidebarCodePreview": {
   "title": "Código",
   "copy": "Copiar",
   "copied": "Copiado",
  },
  "sidebarDocumentPreview": {
   "loading": "Leyendo…",
   "loadMore": "Cargar más",
   "changed": "El fichero ha cambiado; se muestra el contenido anterior.",
   "reloadNow": "Recargar",
   "reload": "Volver a leer el fichero",
   "wrap.enable": "Activar el ajuste de línea",
   "wrap.disable": "Desactivar el ajuste de línea",
   "wrap.aria": "Ajuste de línea",
   "openWith": "Abrir con",
   "viewer.text": "Texto sin formato",
   "resourceUnavailable": "El servicio de recursos de ficheros no está disponible.",
   "rendererUnavailable": "La vista previa de {name} no está disponible.",
   "error.notFound": "No se encuentra el fichero. Puede que se haya movido o borrado.",
   "error.tooLarge": "Esta página supera el límite de {limit} y no se puede leer.",
   "error.notText": "No es un fichero de texto; la vista previa no está disponible por ahora.",
   "error.notRegularFile": "No es un fichero normal; no hay nada que mostrar.",
   "error.unavailable": "Falló la lectura: {message}",
   "retry": "Reintentar",
  },
  "sidebarFiles": {
   "type.label": "Ficheros",
   "guide.title": "Ficheros del espacio de trabajo",
   "guide.description": "Explora los ficheros del espacio de trabajo de esta sesión",
   "loading": "Leyendo…",
   "empty": "Carpeta vacía",
   "truncated": "Hay demasiadas entradas; se muestran sólo algunas.",
   "noWorkspace": "Esta sesión no tiene carpeta de espacio de trabajo.",
   "reload": "Recargar",
   "entry.other": "No es un fichero ni una carpeta, así que no se puede abrir.",
   "error.notFound": "Esa carpeta ya no está. Puede que se haya movido o borrado.",
   "error.outsideWorkspace": "Esa carpeta está fuera del espacio de trabajo, así que la barra lateral no la va a leer.",
   "error.notDirectory": "Eso no es una carpeta.",
   "error.unavailable": "Falló la lectura: {message}",
  },
  "sidebarImage": {
   "title": "Imagen",
   "preview": "Vista previa de imagen: {name}",
   "loading": "Abriendo imagen…",
   "failed": "No se pudo mostrar esta imagen.",
   "unsupported": "La vista previa de imagen necesita el contenido completo del fichero.",
  },
  "sidebarPdf": {
   "title": "PDF",
   "pageImage": "Página {page} del PDF",
   "loading": "Abriendo el PDF…",
   "rendering": "Pintando la página…",
   "failed": "No puedo mostrar el PDF: {message}",
   "password": "Este PDF pide contraseña; las vistas previas con contraseña no están soportadas.",
   "workerFailed": "El proceso que pinta el PDF no ha podido seguir. Vuelve a intentarlo.",
   "unsupported": "Para ver un PDF hace falta el fichero entero.",
   "retry": "Reintentar",
  },
  "sidebarRight": {
   "chrome.expand": "Abrir barra lateral",
   "chrome.expandAria": "Abrir la barra lateral derecha",
   "chrome.collapse": "Plegar barra lateral",
   "chrome.collapseAria": "Plegar la barra lateral derecha",
   "chrome.toFullscreen": "Pantalla completa",
   "chrome.exitFullscreen": "Salir de pantalla completa",
   "dock.emptyPane": "Panel vacío",
   "dock.splitPane": "Dividir",
   "dock.splitPaneDisabled": "Dos paneles es el límite",
   "dock.splitPaneNarrow": "No hay ancho suficiente para dividir, ensancha la barra lateral",
   "dock.closeTab": "Cerrar",
   "dock.addTab": "Pestaña nueva",
   "dock.dockFloat": "Devolver a la barra lateral",
   "dock.closeFloat": "Cerrar",
   "dock.drop.center": "Mover aquí",
   "dock.drop.left": "Añadir división a la izquierda",
   "dock.drop.right": "Añadir división a la derecha",
   "dock.drop.top": "Añadir división arriba",
   "dock.drop.bottom": "Añadir división abajo",
   "tab.guide.title": "Inicio",
   "tab.unavailable": "Aquí todavía no hay nada que pueda ver este tipo de contenido.",
  },
  "skill": {
   "row.title": "Skill",
   "row.running": "Cargando skill",
   "row.failed": "Falló la carga del skill",
   "row.stopped": "Carga del skill detenida",
   "row.instructions": "Instrucciones",
   "row.inspect": "Inspeccionar",
   "menu.userOnly": "sólo usuario",
  },
  "slash.menu": {
   "command": "Comandos",
   "skill": "Skills",
   "subagent": "Subagentes",
   "loading": "Cargando…",
   "drill.aria": "Explorar carpeta",
   "drill.hint": "Explorar carpeta",
   "drill.key": "Tab",
   "crumbs.aria": "Navegación por carpetas",
   "suggestions.aria": "Sugerencias de activación",
  },
  "subagent": {
   "diagnostic.corrupt": "registro de sesión corrupto",
   "diagnostic.unsupported": "versión del registro de subagente no compatible",
   "diagnostic.unavailable": "registro de sesión no disponible temporalmente",
   "duration.seconds": "{seconds}s",
   "duration.minutes": "{minutes}m {seconds}s",
   "duration.hours": "{hours}h {minutes}m {seconds}s",
   "duration.days": "{days}d",
   "duration.daysHours": "{days}d {hours}h",
   "duration.months": "~{months}mes",
   "duration.monthsDays": "~{months}mes {days}d",
   "duration.years": "~{years}a",
   "duration.yearsMonths": "~{years}a {months}mes",
   "duration.exactDays": "{days}d {hours}h {minutes}m {seconds}s",
   "duration.exactTitle": "Duración activa total: {duration}",
   "tokens.thousand": "{value}K",
   "tokens.million": "{value}M",
   "tokens.total": "{value} tok",
   "loading.label": "Cargando subagentes…",
   "loading.aria": "Cargando subagentes",
   "load.error": "No se pudieron cargar los subagentes",
   "retry": "Reintentar",
   "mode.oneShot": "de una sola vez",
   "mode.continuable": "continuable",
   "activity.running": "en marcha",
   "activity.inactive": "inactivo",
   "branch.collapse": "Contraer {label} descendientes",
   "branch.expand": "Expandir {label} descendientes",
   "count.total.one": "{count} subagente",
   "count.total.other": "{count} subagentes",
   "count.running.one": "{count} subagente en marcha",
   "count.running.other": "{count} subagentes en marcha",
   "switcher.aria": "Cambiar de subagente: {title}",
   "tree.aria": "Sesiones de subagentes",
   "readonly.oneShot.title": "Registro de subagente de una sola vez",
   "readonly.title": "Este subagente, por ahora, es sólo para mirar",
   "readonly.oneShot.body": "Las tareas de una sola vez no admiten mensajes posteriores; aquí tienes el registro completo de la ejecución.",
   "readonly.body": "La sesión padre está desconectada; vuelve a abrirla para seguir enviando mensajes.",
  },
  "trajectory": {
   "view.trajectory": "Actividad",
   "toolbar.aria": "Barra de herramientas de la actividad",
   "toolbar.duration": "Duración",
   "toolbar.useActualDuration": "Usar la duración real",
   "toolbar.useEqualWidth": "Usar operaciones de ancho igual",
   "toolbar.actualTime": "Tiempo real",
   "toolbar.turns": "Vueltas",
   "toolbar.expandTurns": "Expandir vueltas",
   "toolbar.collapseTurns": "Contraer vueltas",
   "toolbar.calls": "Llamadas",
   "toolbar.expandCalls": "Expandir llamadas",
   "toolbar.collapseCalls": "Contraer llamadas",
   "toolbar.search": "Buscar en la actividad",
   "toolbar.searchPlaceholder": "Buscar",
   "kind.system": "SISTEMA",
   "kind.user": "USUARIO",
   "kind.context": "CONTEXTO",
   "kind.compacted": "COMPACTADO",
   "kind.message": "Mensaje",
   "kind.assistant": "ASISTENTE",
   "kind.tool": "HERRAMIENTA",
   "kind.subtool": "SUBHERRAMIENTA",
   "kind.sub": "Sub",
   "column.input": "Entrada",
   "column.output": "Salida",
   "column.think": "Rumiar",
   "column.time": "Tiempo",
   "column.model": "Modelo",
   "column.tools": "Herramientas",
   "turn.label": "Vuelta {turn}",
   "section.betweenTurns": "Entre vueltas",
   "group.message": "Mensaje",
   "group.step": "Paso {step}",
   "group.compaction": "Compactación {seq}",
   "status.failed": "Fallido",
   "status.pending": "Pendiente",
   "status.completed": "Completado",
   "timing.notAvailable": "No disponible",
   "timing.notRecorded": "Sin registrar",
   "timing.stepStartUnavailable": "Inicio del paso no disponible",
   "timing.firstTokenUnavailable": "Primer token no disponible",
   "timing.usageUnavailable": "Uso no disponible",
   "timing.outputTokensUnavailable": "Tokens de salida no disponibles",
   "timing.durationTooShort": "Duración demasiado corta",
   "timing.showLocalTime": "Mostrar la hora local",
   "timing.showUnixTimestamp": "Mostrar la marca de tiempo Unix",
   "timing.started": "Iniciado",
   "timing.totalDuration": "Duración total",
   "timing.ttft": "TTFT",
   "timing.generation": "Generación",
   "timing.throughput": "Rendimiento",
   "timing.duration": "Duración",
   "timing.source": "Origen de los tiempos",
   "timing.sessionTimestamps": "Marcas de tiempo de la sesión",
   "timing.sessionTimestampsRunning": "Marcas de tiempo de la sesión (en marcha)",
   "timing.request": "Tiempos de la petición",
   "unit.milliseconds": "{value} ms",
   "unit.seconds": "{value} s",
   "unit.tokens": "{value} tok",
   "unit.tokensPerSecond": "{value} tok/s",
   "usage.tokens": "Tokens",
   "usage.reasoning": "Razonamiento",
   "usage.content": "Contenido",
   "usage.notReported": "Uso no informado",
   "usage.input": "Entrada",
   "usage.cached": "En caché",
   "usage.cacheCreated": "Caché creada",
   "usage.other": "Otros",
   "usage.output": "Salida",
   "usage.thisRequest": "Esta petición",
   "usage.sessionCumulative": "Acumulado de la sesión",
   "options.notRecorded": "Opciones sin registrar",
   "options.json": "JSON de opciones de la petición",
   "source.unknown": "Desconocido",
   "source.user": "Usuario",
   "source.plugin": "Plugin",
   "source.pluginNamed": "Plugin · {plugin}",
   "source.goal": "Objetivo",
   "source.goalRound": "Objetivo · Ronda {round}",
   "source.notRecorded": "Origen sin registrar",
   "source.messageJson": "JSON del origen del mensaje",
   "tab.summary": "Resumen",
   "tab.rawOutput": "Salida en bruto",
   "tab.preview": "Vista previa",
   "tab.raw": "En bruto",
   "tab.source": "Origen",
   "tab.payload": "Carga útil",
   "tab.result": "Resultado",
   "tab.schema": "Esquema",
   "tab.timing": "Tiempos",
   "tab.diff": "Diferencias",
   "tab.systemPrompt": "Instrucciones",
   "tab.tools": "Herramientas",
   "tab.options": "Opciones",
   "tab.usage": "Uso",
   "record.toolCallOnly": "(sólo llamada a herramienta)",
   "record.noContent": "Sin contenido",
   "record.noPayload": "No se capturó ninguna carga útil",
   "record.noResult": "No se capturó ningún resultado",
   "record.noOutput": "Sin salida",
   "record.schemaUnavailable": "Esquema no disponible",
   "record.parameters": "Parámetros",
   "record.resultJson": "JSON del resultado",
   "record.json": "JSON",
   "record.parametersJson": "JSON de parámetros",
   "record.namedParametersJson": "JSON de parámetros de {name}",
   "record.payloadJson": "JSON de la carga útil",
   "record.outputJson": "JSON del resultado",
   "record.thinking": "Razonamiento",
   "record.systemPromptMissing": "Esta petición no trae instrucciones",
   "record.toolsMissing": "Esta petición no trae herramientas",
   "record.systemPrompt": "Instrucciones",
   "record.tools": "Herramientas",
   "block.openSummary": "Abrir el resumen de llamadas a herramienta del bloque #{index}",
   "block.openSummaryTitle": "Abrir el resumen de llamadas a herramienta",
   "block.label": "Bloque #{index} {type}",
   "history.loadingTrajectory": "Cargando la actividad…",
   "history.loadingEarlier": "Cargando el historial anterior…",
   "history.loadingEarlierAria": "Cargando el historial anterior…",
   "history.loadEarlier": "Cargar el historial anterior",
   "history.clickToLoadEarlier": "Haz clic para cargar el historial anterior",
   "request.label": "Petición #{request}",
   "request.labelCompaction": "Petición #{request} · Compactación",
   "request.compaction": "Compactación · {section}",
   "request.compactionPurpose": "Compactación",
   "request.retryProgress": "{retry} de {maximum}",
   "request.collapsedSummary": "Resumen contraído ({kind}), {summary}",
   "request.collapsedTurn": "vuelta",
   "request.collapsedAssistant": "asistente",
   "request.rowAria": "{request}{kind}, {content}",
   "request.rowPrefix": "Petición {request}, ",
   "request.rowAriaCompaction": "Petición {request}, compactación",
   "request.noContent": "sin contenido",
   "summary.toolCalls.one": "{count} llamada a herramienta",
   "summary.toolCalls.other": "{count} llamadas a herramienta",
   "summary.steps.one": "{count} paso",
   "summary.steps.other": "{count} pasos",
   "details.event": "Detalles del evento",
   "details.resize": "Cambiar el tamaño de los detalles del evento",
   "details.resizeTitle": "Arrastra para cambiar el tamaño. Haz doble clic para restablecerlo.",
   "details.close": "Cerrar los detalles",
   "details.status": "Estado",
   "details.purpose": "Propósito",
   "details.provider": "Proveedor",
   "details.model": "Modelo",
   "details.toolCalls": "Llamadas a herramienta",
   "details.subtoolCalls": "Llamadas a subherramienta",
   "details.error": "Error",
   "details.failure.auth": "La clave de API no es válida",
   "details.retry": "Reintentar",
   "details.scheduled": "Programado",
   "details.retryDelay": "Espera antes de reintentar",
   "details.result": "Resultado",
   "details.compacted": "Compactado",
   "details.assistantMessage": "Mensaje del asistente",
   "details.source": "Origen",
   "details.hierarchy": "Jerarquía",
   "details.toolCall": "Llamada a herramienta",
   "timeline.aria": "Cronología de la actividad",
   "timeline.overviewAria": "Vista general de la cronología; arrastra en horizontal para centrar los eventos",
   "timeline.noTimingData": "Sin datos de tiempos",
   "timeline.total": "Total {duration}",
   "timeline.started": "Iniciado {time}",
   "timeline.ttftDecoding": "TTFT {ttft} · Decodificación {decoding}",
   "layout.compacting": "Compactando el contexto…",
   "layout.compactionFailed": "La compactación falló",
   "layout.compacted": "Contexto compactado",
   "layout.toolCallOnly": "Sólo llamada a herramienta",
   "layout.imageOnly": "Imágenes ×{count}",
   "layout.fileAttachments": "Ficheros ×{count}",
   "layout.initialSystemPrompt": "Instrucciones iniciales",
   "layout.systemPromptUpdated": "Instrucciones actualizadas",
   "layout.toolsUpdated": "Herramientas actualizadas",
   "layout.systemPromptAndToolsUpdated": "Instrucciones y herramientas actualizadas",
   "layout.compactionInterrupted": "La compactación se interrumpió antes de terminar.",
  },
  "workflowRun": {
   "run.title": "{name}",
   "run.members.one": "{count} miembro",
   "run.members.other": "{count} miembros",
   "run.empty": "No ha arrancado ningún miembro",
   "phase.unassigned": "Sin fase",
   "phase.empty": "Nombre de fase vacío",
   "statusCount.running": "En marcha {count}",
   "statusCount.completed": "Completado {count}",
   "statusCount.failed": "Fallido {count}",
   "statusCount.cancelled": "Cancelado {count}",
   "statusCount.interrupted": "Interrumpido {count}",
   "member.empty": "Nombre de miembro vacío",
   "member.open": "Abrir {name}",
   "status.running": "En marcha",
   "status.completed": "Completado",
   "status.failed": "Fallido",
   "status.cancelled": "Cancelado",
   "status.interrupted": "Interrumpido",
  },
  "workspace": {
   "group.ungrouped": "Sin grupo",
   "session.new": "Nueva sesión",
   "section.workspaces": "Espacios de trabajo",
   "section.sessions": "Sesiones",
   "viewOptions.label": "Opciones de vista",
   "groupBy.label": "Agrupar por",
   "groupBy.workspace": "Espacio de trabajo",
   "groupBy.flat": "En una sola lista",
   "orderBy.label": "Ordenar por",
   "orderBy.manual": "Manual",
   "orderBy.updated": "Última actualización",
   "sessions.expand": "Mostrar {n} sesiones más",
   "sessions.collapse": "Mostrar menos",
   "empty.none": "Todavía no hay sesiones",
   "empty.noMatches": "Sin coincidencias",
   "workspace.add": "Añadir espacio de trabajo",
   "search.sessions.aria": "Buscar sesiones",
   "search.placeholder": "Buscar sesiones...",
   "search.clear": "Limpiar búsqueda",
   "search.results.aria": "Resultados de la búsqueda",
   "search.pending": "Buscando en el historial de sesiones…",
   "search.unavailable": "La búsqueda por contenido no está disponible temporalmente. Se muestran las coincidencias por nombre.",
   "search.noMatches": "No hay sesiones que coincidan",
   "search.hasMore": "Se muestran los primeros {n} resultados. Afina la búsqueda.",
   "menu.addWorkspace": "Añadir espacio de trabajo…",
   "picker.loading": "Cargando espacios de trabajo…",
   "conflict.named": "Ya existe un espacio de trabajo llamado “{name}”.",
   "folderError.title": "No se pudo abrir la carpeta",
   "folderError.retry": "Elegir otra vez",
   "rename": "Cambiar nombre",
   "rename.workspace.title": "Cambiar nombre del espacio de trabajo",
   "rename.session.title": "Cambiar nombre de la sesión",
   "field.workspaceName": "Nombre del espacio de trabajo",
   "field.sessionName": "Nombre de la sesión",
   "delete.workspace": "Borrar espacio de trabajo",
   "delete.desc": "Esto quita “{name}” de la lista de espacios de trabajo. La carpeta y los registros de sesión se conservarán. Sus sesiones aparecerán en Sin grupo.",
   "delete.pending": "Borrando el espacio de trabajo…",
   "menu.fork": "Bifurcar sesión",
   "menu.archiveSession": "Archivar sesión",
   "sessions.count.one": "{n} sesión",
   "sessions.count.other": "{n} sesiones",
   "actions.workspace.aria": "Acciones del espacio de trabajo {name}",
   "actions.session.aria": "Acciones de la sesión {name}",
   "actions.newSession.aria": "Nueva sesión en {name}",
   "status.running": "En marcha",
   "status.subagentsRunning.one": "{n} subagente en marcha",
   "status.subagentsRunning.other": "{n} subagentes en marcha",
   "status.idle": "En reposo",
   "status.waitingApproval": "Esperando aprobación",
   "status.planReview": "Plan pendiente de revisión",
   "status.waitingAnswer": "Esperando respuesta",
   "status.completed": "Completada",
   "schedule.active": "Tiene una tarea programada activa",
   "hover.created": "Creado {time}",
   "hover.copied": "Copiado",
   "date.ymd": "{y}-{m}-{d}",
   "time.now": "ahora",
   "time.minutes": "{n}min",
   "time.hours": "{n}h",
   "time.days": "{n}d",
   "time.months": "{n}mes",
   "time.years": "{n}a",
   "time.ago": "hace {t}",
  },
};
